[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

# https://github.com/briansmith/ring/issues/1514#issuecomment-1258562375
[target.aarch64-pc-windows-msvc.patch.crates-io]
ring = { git="https://github.com/awakecoding/ring", branch="0.16.20_alpha" }
