[workspace]
resolver = "2"
members = [
    "erpc",
    "http-server",
    "http-client-wasm",
    "transpiler",
    "bindings/node-api",
    "bindings/browser"
]

[profile.release.package.browser]
opt-level = "s"

[profile.release]
lto = true