blank_issues_enabled: false
contact_links:
  - name: Suggest a feature
    url: https://github.com/m1212e/easy-rpc/discussions/categories/ideas-suggestions
    about: Please use the ideas tab of the discussion section to request and discuss new features.
  - name: Ask a question or recieve help
    url: https://github.com/m1212e/easy-rpc/discussions/categories/help
    about: Please use the help tab of the discussion section to recieve help and ask questions.
