[package]
name = "erpc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
bytes = "1"
log = "0.4"
nanoid = "0.4.0"