on:
  push:
    branches: ["main"]
env:
  RUSTFLAGS: -Cinstrument-coverage
  CARGO_INCREMENTAL: '0'
  LLVM_PROFILE_FILE: coverage/tmp/cargo-test-%p-%m.profraw
jobs:
  rust_coverage:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          command: clean
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
      - id: coverage  
        uses: actions-rs/grcov@v0.1
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: ${{ steps.coverage.outputs.report }}
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
