on:
  push:
    branches: ["main"]

jobs:
  tarpaulin_coverage:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install sudo package
        run: apt update && apt install sudo
      - name: Set up GCC
        run: sudo apt install gcc-multilib
      - name: Generate code coverage
        env:
          RUSTFLAGS: -Cinstrument-coverage
          LLVM_PROFILE_FILE: coverage/tmp/cargo-test-%p-%m.profraw
        run: | 
             rustup component add llvm-tools-preview
             cargo build
             cargo test
             grcov coverage/tmp --binary-path ./target/debug -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o coverage/lcov.info
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/lcov.info
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
