on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test
  node-api_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./bindings/node-api
        run: npm ci
      - name: Run tests
        working-directory: ./bindings/node-api
        run: npm run test
