on:
  release:
    types: [created]

jobs:
  transpiler_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: transpiler
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --verbose
  transpiler_build:
    needs: transpiler_test
    strategy:
      fail-fast: false
      matrix:
        platform:
          - host: windows-latest
            target: x86_64-pc-windows-msvc
          - host: windows-latest
            target: aarch64-pc-windows-msvc
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: macos-latest
            target: aarch64-apple-darwin
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - host: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
    name: ${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.host }}
    steps:
      - uses: actions/checkout@v3
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: ${{ matrix.platform.target }}-cargo-${{ matrix.platform.host }}
      - name: Build
        run: cargo build --package transpiler --release
      - name: Rename
        if: matrix.platform.host != 'windows-latest'
        run: mv target/release/easy-rpc target/release/easy-rpc-${{ matrix.platform.target }}
      - name: Rename WIN
        if: matrix.platform.host == 'windows-latest'
        run: mv target/release/easy-rpc.exe target/release/easy-rpc-${{ matrix.platform.target }}.exe
      - name: Upload
        if: matrix.platform.host != 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/easy-rpc-${{ matrix.platform.target }}
      - name: Upload WIN
        if: matrix.platform.host == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/easy-rpc-${{ matrix.platform.target }}.exe
