on:
  push:
    branches: ["main"]
    paths:
      - "transpiler/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  transpiler_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: transpiler
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --verbose
